const WEBHOOK_TYPES = {
  AUTH: 'auth',
  SYNC: 'sync',
  FORWARD: 'forward',
};

const AUTH_OPERATIONS = {
  CREATION: 'creation',
  OVERRIDE: 'override',
  REFRESH: 'refresh',
};

const SYNC_TYPES = {
  INITIAL: 'INITIAL',
  INCREMENTAL: 'INCREMENTAL',
  WEBHOOK: 'WEBHOOK',
};

const AUTH_MODES = {
  OAUTH2: 'OAUTH2',
  BASIC: 'BASIC',
  API_KEY: 'API_KEY',
  OAUTH1: 'OAUTH1',
};

const ENVIRONMENTS = {
  DEV: 'DEV',
  PROD: 'PROD',
  STAGING: 'STAGING',
};

const PROCESSABLE_WEBHOOK_TYPES = new Set([
  WEBHOOK_TYPES.AUTH,
  WEBHOOK_TYPES.SYNC,
  WEBHOOK_TYPES.FORWARD,
  WEBHOOK_TYPES.CONNECTION_ACTIVATED,
]);

const CRITICAL_AUTH_OPERATIONS = new Set([
  AUTH_OPERATIONS.CREATION,
  AUTH_OPERATIONS.REFRESH,
]);

module.exports = {
  WEBHOOK_TYPES,
  AUTH_OPERATIONS,
  SYNC_TYPES,
  AUTH_MODES,
  ENVIRONMENTS,
  PROCESSABLE_WEBHOOK_TYPES,
  CRITICAL_AUTH_OPERATIONS,
};
